### ISSUE TITLE
Option to disable/enable pagination 

### ISSUE THREAD

**Issue by arvida** [kidpollo/tanker#19]
Basically I would like to do queries without pagination turned on, so I just get an array of all the documents from #search. I also think new users don't expect the results to be paginated by default?

I am about to go a head and implement this, just want to check with you guys first if you have any thoughts on how it should work and if its a feature for the master branch? I few things I was thinking about:
- Should pagination be enabled/disabled by default?
- Should it be a setting on Tanker.configuration or an option per #search call?
- Maybe you should be able to select pagination lib if enabled? Like having a setting that says 
  `Tanker.configuration.pagination_backend = :will_paginate` or `Tanker.configuration.pagination_backend = :kaminari` (haven't checked much on the kaminari source yet, so might not be possible to use that lib..)

So, any thoughts on this? =)

**Comment by kidpollo** [comment]
I love the interchangeable pagination backend options I dont like pagination to be configurable. It should be there by default unless changed on a specific search call. Lets have it so that :per_page => 0 means do not paginate.

Ideas?

Send me your pull request I will gladly add it

**Comment by kidpollo** [comment]
Tests required of course

**Comment by arvida** [comment]
Ok, great! Will try to get some code done for this.

I am thinking that :per_page => 0 might be a bit undescriptive. An idea would be to do something like:
`Topic.search_tank('blah', :paginate => { :page => 1, :per_page => 25 })` when you want to set options for pagination and `Topic.search_tank('blah', :paginate => false)`  when you want to disable it. 
Just adding the `:paginate => false` option might be enough? 

We should def keep the current way to set :page / :per_page so we don't break any existing apps.

**Comment by kidpollo** [comment]
cool!

Do it

## 

Francisco Viramontes
Sent with Sparrow

**Comment by coryschires** [comment]
As a workaround, set the pagination to 5000:

  Order.search_tank(params[:search], :per_page => 5000)
