### ISSUE TITLE
What happens when IndexTank is down?

### ISSUE THREAD

**Issue by samuelhwong** [kidpollo/tanker#22]
Hi, I'm a beginner at Rails and I was wondering how errors are handled in Tanker? For example, what happens when the IndexTank API is unreachable? Will my model fail to save? Ideally, my model data would be saved regardless and any failed attempts at indexing would be placed in a queue for retrying later.

Thanks!

**Comment by arvida** [comment]
Hi, 

It depends on how you implement your models =) I think a good way would be to put the `update_tank_indexes` call in a delayed job, for example:

```
class Page < ActiveRecord::Base
  include Tanker
  after_save proc { |page| page.delay.update_tank_indexes } 
end
```

This way the user doesn't have to wait for the call to IndexTanks's servers to finish and delayed_job will try to redo the job if it fails. You can read more about delayed_job here on Github: https://github.com/collectiveidea/delayed_job

It might be a good idea to have something like a ”best praticies” page and/or some documentation on this in the wiki?

**Comment by kidpollo** [comment]
Thanks @arvida I could not have answered it better. Index tank is pretty solid. I know those guys they really know their shit :D

**Comment by samuelhwong** [comment]
That's exactly what I needed to hear. Thanks for the tip!
