### ISSUE TITLE
Categories

### ISSUE THREAD

**Issue by kidpollo** [kidpollo/tanker#23]

**Comment by shiftb** [comment]
Great gem! I really need this feature. Let me know if there's anything I can do to help and I'll try my best to do it.

**Comment by kidpollo** [comment]
The idea I have is that the collection returned by every search_tank call has a method that returns the categories. That is I think relatively easy. The problem is defining the api to set up the categories for a particular model

**Comment by shiftb** [comment]
Looks like you could straight up copy what you've done for the fields data and the `indexes` method inside `tankit`.
Maybe provide a `categorizes` or `categories` method (I don't know if indexes is supposed to be a verb convention or just a plural noun) that accepts a name and then stores the value of that method or a block if provided.

**Comment by oleksify** [comment]
Really need this feature, when this is planned to be implemented?

**Comment by kidpollo** [comment]
I am almost finished with this feature! I hope to ship it during this week

**Comment by kidpollo** [comment]
Hey! @devilcoders @shiftb 

I am very close to finishing the categories feature. Could you guys give me your opinions on my last commit and even test it out in your applications?

I am still not sure if the category_filters search option is the best approach for this. 

Please find usage details in the readme and integration specs.

**Comment by oleksify** [comment]
Still cannot figure out how to dynamically add a batch of categories to model. It seems that current implementation let you only  add categories one by one and naming them by yourself. I have a hash of categories from database, how can I add them?

**Comment by codebrew** [comment]
If you pass :paginate => false to your search then you currently can't access the facets (categories), the results are being loaded from the db and facets are completely lost.

**Comment by iladriano** [comment]
@codebrew I suggested something like https://github.com/kidpollo/tanker/pull/40 to address that, still missing the tests :(

**Comment by kidpollo** [comment]
ahhh sorry @adranai I think I am not understanding the approach could you please explain further?

**Comment by iladriano** [comment]
Yes, the approach:
- splits "Tanker.search" into two parts "Tanker.search_results" and "Tanker.instantiate" (search turns to be instantiate(search_results(...)))
- exposes most of "Tanker.search" internal state (especially "results" from indextank) via SearchState (which is returned by Tanker.search_results)
- allows the user to obtain extra metadata with SearchState.results (example results["didyoumean"], results["search_time"] etc.)
- also as a consequence, obtaining categories doesn't enforce requiring pagination

**Comment by kidpollo** [comment]
ahhh ok! well I'll try to add this onto the categories feature in the following days
