### ISSUE TITLE
Can't use tanker 1.1.0

### ISSUE THREAD

**Issue by oleksify** [kidpollo/tanker#24]
<code>
/Users/devilcoders/.rvm/gems/ruby-1.9.2-p180/gems/tanker-1.1.0/lib/tanker/railtie.rb:13:in `block in <class:Railtie>': undefined local variable or method`setup_tanker_configuration' for Tanker::Railtie:Class (NameError)
    from /Users/devilcoders/.rvm/gems/ruby-1.9.2-p180/gems/activesupport-3.0.7/lib/active_support/lazy_load_hooks.rb:34:in `call'
    from /Users/devilcoders/.rvm/gems/ruby-1.9.2-p180/gems/activesupport-3.0.7/lib/active_support/lazy_load_hooks.rb:34:in`execute_hook'
    from /Users/devilcoders/.rvm/gems/ruby-1.9.2-p180/gems/activesupport-3.0.7/lib/active_support/lazy_load_hooks.rb:43:in `block in run_load_hooks'
    from /Users/devilcoders/.rvm/gems/ruby-1.9.2-p180/gems/activesupport-3.0.7/lib/active_support/lazy_load_hooks.rb:42:in`each'
    from /Users/devilcoders/.rvm/gems/ruby-1.9.2-p180/gems/activesupport-3.0.7/lib/active_support/lazy_load_hooks.rb:42:in `run_load_hooks'
    from /Users/devilcoders/.rvm/gems/ruby-1.9.2-p180/gems/railties-3.0.7/lib/rails/application/finisher.rb:46:in`block in module:Finisher'
    from /Users/devilcoders/.rvm/gems/ruby-1.9.2-p180/gems/railties-3.0.7/lib/rails/initializable.rb:25:in `instance_exec'
    from /Users/devilcoders/.rvm/gems/ruby-1.9.2-p180/gems/railties-3.0.7/lib/rails/initializable.rb:25:in`run'
    from /Users/devilcoders/.rvm/gems/ruby-1.9.2-p180/gems/railties-3.0.7/lib/rails/initializable.rb:50:in `block in run_initializers'
    from /Users/devilcoders/.rvm/gems/ruby-1.9.2-p180/gems/railties-3.0.7/lib/rails/initializable.rb:49:in`each'
    from /Users/devilcoders/.rvm/gems/ruby-1.9.2-p180/gems/railties-3.0.7/lib/rails/initializable.rb:49:in `run_initializers'
    from /Users/devilcoders/.rvm/gems/ruby-1.9.2-p180/gems/railties-3.0.7/lib/rails/application.rb:134:in`initialize!'
    from /Users/devilcoders/.rvm/gems/ruby-1.9.2-p180/gems/railties-3.0.7/lib/rails/application.rb:77:in `method_missing'
    from /Volumes/data/Projects/Code/Work/DevilCoders/muzarena/config/environment.rb:5:in`<top (required)>'
    from /Users/devilcoders/.rvm/gems/ruby-1.9.2-p180/gems/activesupport-3.0.7/lib/active_support/dependencies.rb:239:in `require'
    from /Users/devilcoders/.rvm/gems/ruby-1.9.2-p180/gems/activesupport-3.0.7/lib/active_support/dependencies.rb:239:in`block in require'
    from /Users/devilcoders/.rvm/gems/ruby-1.9.2-p180/gems/activesupport-3.0.7/lib/active_support/dependencies.rb:225:in `block in load_dependency'
    from /Users/devilcoders/.rvm/gems/ruby-1.9.2-p180/gems/activesupport-3.0.7/lib/active_support/dependencies.rb:596:in`new_constants_in'
    from /Users/devilcoders/.rvm/gems/ruby-1.9.2-p180/gems/activesupport-3.0.7/lib/active_support/dependencies.rb:225:in `load_dependency'
    from /Users/devilcoders/.rvm/gems/ruby-1.9.2-p180/gems/activesupport-3.0.7/lib/active_support/dependencies.rb:239:in`require'
    from /Users/devilcoders/.rvm/gems/ruby-1.9.2-p180/gems/railties-3.0.7/lib/rails/application.rb:103:in `require_environment!'
    from /Users/devilcoders/.rvm/gems/ruby-1.9.2-p180/gems/railties-3.0.7/lib/rails/commands.rb:16:in`<top (required)>'
    from script/rails:6:in `require'
    from script/rails:6:in`<main>'
</code>

**Comment by kidpollo** [comment]
Could you provide mor information on this?

Did you upgrade and it stoped working. Is this the first time you are using the gem and is it configured propperly?

**Comment by oleksify** [comment]
Yes, First I tried to use it from github - same issue. I use version 1.0.0 - everything is ok. Now I see it is updated, I update it and it stop working.

Please, help me, as I need it for work, writing search plugin for spreecommerce

**Comment by kidpollo** [comment]
Ok thanks I see the problem will fix it in a bit

**Comment by oleksify** [comment]
Thanks!

**Comment by kidpollo** [comment]
could you update your gemfile temprarily to use this 
gem 'tanker', :git => 'git://github.com/kidpollo/tanker.git', :ref => '8dc674ae102cb2efbfe7'

lmk if it solves the issue, I am unable to reproduce it right now

**Comment by oleksify** [comment]
nope, same issue:

<code>
/Users/devilcoders/.rvm/gems/ruby-1.9.2-p180/bundler/gems/tanker-8dc674ae102c/lib/tanker/railtie.rb:9:in `block in <class:Railtie>': undefined local variable or method`setup_tanker_configuration' for #Tanker::Railtie:0x000001017dd460 (NameError)
    from /Users/devilcoders/.rvm/gems/ruby-1.9.2-p180/gems/railties-3.0.7/lib/rails/initializable.rb:25:in `instance_exec'
    from /Users/devilcoders/.rvm/gems/ruby-1.9.2-p180/gems/railties-3.0.7/lib/rails/initializable.rb:25:in`run'
    from /Users/devilcoders/.rvm/gems/ruby-1.9.2-p180/gems/railties-3.0.7/lib/rails/initializable.rb:50:in `block in run_initializers'
    from /Users/devilcoders/.rvm/gems/ruby-1.9.2-p180/gems/railties-3.0.7/lib/rails/initializable.rb:49:in`each'
    from /Users/devilcoders/.rvm/gems/ruby-1.9.2-p180/gems/railties-3.0.7/lib/rails/initializable.rb:49:in `run_initializers'
    from /Users/devilcoders/.rvm/gems/ruby-1.9.2-p180/gems/railties-3.0.7/lib/rails/application.rb:134:in`initialize!'
    from /Users/devilcoders/.rvm/gems/ruby-1.9.2-p180/gems/railties-3.0.7/lib/rails/application.rb:77:in `method_missing'
    from /Volumes/data/Projects/Code/Work/DevilCoders/muzarena/config/environment.rb:5:in`<top (required)>'
    from /Users/devilcoders/.rvm/gems/ruby-1.9.2-p180/gems/activesupport-3.0.7/lib/active_support/dependencies.rb:239:in `require'
    from /Users/devilcoders/.rvm/gems/ruby-1.9.2-p180/gems/activesupport-3.0.7/lib/active_support/dependencies.rb:239:in`block in require'
    from /Users/devilcoders/.rvm/gems/ruby-1.9.2-p180/gems/activesupport-3.0.7/lib/active_support/dependencies.rb:225:in `block in load_dependency'
    from /Users/devilcoders/.rvm/gems/ruby-1.9.2-p180/gems/activesupport-3.0.7/lib/active_support/dependencies.rb:596:in`new_constants_in'
    from /Users/devilcoders/.rvm/gems/ruby-1.9.2-p180/gems/activesupport-3.0.7/lib/active_support/dependencies.rb:225:in `load_dependency'
    from /Users/devilcoders/.rvm/gems/ruby-1.9.2-p180/gems/activesupport-3.0.7/lib/active_support/dependencies.rb:239:in`require'
    from /Users/devilcoders/.rvm/gems/ruby-1.9.2-p180/gems/railties-3.0.7/lib/rails/application.rb:103:in `require_environment!'
    from /Users/devilcoders/.rvm/gems/ruby-1.9.2-p180/gems/railties-3.0.7/lib/rails/commands.rb:16:in`<top (required)>'
    from script/rails:6:in `require'
    from script/rails:6:in`<main>'

</code>

**Comment by kidpollo** [comment]
hmm try this reff then

f6d6ac3df9346fb4f2de

its anasty patch for now

**Comment by oleksify** [comment]
Works!
