### ISSUE TITLE
1.8.7 compatibility

### ISSUE THREAD

**Issue by ghost** [kidpollo/tanker#26]
Hi there, I just started using Indextank on Heroku recently, and google points me to use this gem rather than thinkingtank (the one suggested by indextank). 

Anyway, I added tanker into my Gemfile, ran bundle install, tried to follow through the example, and try to run the rake task.
That is where I ran into the rake task error. 

I'm using rake gem version 0.8.7 and it gave me this error when trying to run 'rake' command:
<code>Rake tasks fetching failed with (APP_PATH)
Tanker-1.1.1/lib/Tanker.rb:289:syntax error, unexpected ')', expecting '='</code>

So, I took a look at the library and there seems to be a missing ampersand on the block for ModelConfig's initialize method, tried to fix that (rake runs now) and ran into ArgumentError (3 for 2) when trying to run the rake tanker:reindex task. I'm pretty new to Ruby so I'm not sure how to proceed.
Tried running version 1.0.9, no luck. Reverted to 1.0.0 and it ran fine.
Have I been doing something very wrong or is the gem broken?

**Comment by kidpollo** [comment]
hmm seems like a legitimate bug I will look into it. Just out of curiosity which version of ruby are u using?

**Comment by kidpollo** [comment]
the problem is that recent pull request I merged is not ruby 1.8.7 compatible I am going to add rvm environments to be able to test it in multiple rubies. 

In the meantime you can try to use it in 1.9.2 or submit a patch :P

sorry for the inconvenience

I will try to fix this over the weekend

**Comment by slothbear** [comment]
I made a couple of changes that allowed my project to work and (all but one) specs to pass. The changes are described in issue #27.

**Comment by ghost** [comment]
All right. Updated my 'tanker' from the latest commit and it works well now. Thanks!
