### ISSUE TITLE
Can tanker drop records that can't be found?

### ISSUE THREAD

**Issue by aokolish** [kidpollo/tanker#53]
From time to time, things are getting into my index that do not exist in my database. When this happens, I get an ActiveRecord::RecordNotFound exception (I'm using rails). I have fixed this locally by monkey patching the instantiate_results_from_db method. I know I could use rescue to handle that exception, but it seems like a shame when tanker could return 1,000 id's and one of them might not be in the database anymore. Here is how I fixed it:

``` ruby
#tanker.rb - instantiate_results_from_db
...
id_map.each do |klass, ids|
  # narrow ids down to records that exist 
  ids = ids.find_all {|x| constantize(klass).exists? x}
  ...
end
```

I hear this is what Sunspot does. What do you think? I suppose it could be configurable.

**Comment by jon-n** [comment]
I agree that it would be great if there  a way to handle this. 

 I was running into a very similar problem where items were getting deleted out of my database, but they still existed as documents in the Indextank index.  So when using the search_tank method, it was throwing the RecordNotFound error.  

In my case, it would be a lot better if search_tank returned all of the objects that do exist, even though there may be some that are missing.

**Comment by samuelhwong** [comment]
Shouldn't these scenarios be handled by

```
after_save :update_tank_indexes
after_destroy :delete_tank_indexes
```

?

**Comment by aokolish** [comment]
Yes, you would think so. This would essentially be a fail safe. The issue seems to come up most often in the test environment. When it happens, several of my tests fail and I have to manually find and remove things in the index.

**Comment by kidpollo** [comment]
Just execute it for the environment you need it for
