### ISSUE TITLE
Configuration

### ISSUE THREAD

**Issue by yragab** [kidpollo/tanker#55]
Hi guys,

Thank you very much for this work. I have a question: IndexTank isn't signing up new users. How do I get an api url? Is there a proper way to get around this? I am deploying my app on Heroku and I keep getting this message when I try to activate indexTank " That add-on is only available to selected users". Is this related to IndexTank's acquisition? Any idea how will the situation be?

Thank you very much!

**Comment by kidpollo** [comment]
I think there will be no more api keys aver again :(. Tanker might go on depending on the plans on Open Sourcing Index Tank.
