### ISSUE TITLE
IndexTank::HttpCodeException: Incorrect api call

### ISSUE THREAD

**Issue by mightylucene** [kidpollo/tanker#73]
I am using indextank-1.1.6 and facing above exception

following is my model definition

  include Tanker
  tankit "regions" do
    indexes :name
    indexes :full_name
    indexes :slug  
  end

trace is like below

IndexTank::HttpCodeException: Incorrect api call
/home/loken/.rvm/gems/ruby-2.1.0@corental/gems/tanker-1.1.6/lib/indextank_client.rb:64:in `execute'
/home/loken/.rvm/gems/ruby-2.1.0@corental/gems/tanker-1.1.6/lib/indextank_client.rb:22:in`PUT'
/home/loken/.rvm/gems/ruby-2.1.0@corental/gems/tanker-1.1.6/lib/indextank_client.rb:143:in `add_documents'
/home/loken/.rvm/gems/ruby-2.1.0@corental/gems/tanker-1.1.6/lib/tanker.rb:61:in`batch_update'
/home/loken/.rvm/gems/ruby-2.1.0@corental/gems/tanker-1.1.6/lib/tanker.rb:302:in `block in tanker_reindex'
/home/loken/.rvm/gems/ruby-2.1.0@corental/gems/tanker-1.1.6/lib/tanker.rb:301:in`each'
/home/loken/.rvm/gems/ruby-2.1.0@corental/gems/tanker-1.1.6/lib/tanker.rb:301:in `each_with_index'
/home/loken/.rvm/gems/ruby-2.1.0@corental/gems/tanker-1.1.6/lib/tanker.rb:301:in`tanker_reindex'
/home/loken/.rvm/gems/ruby-2.1.0@corental/gems/tanker-1.1.6/lib/tanker/utilities.rb:39:in `block in reindex_all_models'
/home/loken/.rvm/gems/ruby-2.1.0@corental/gems/tanker-1.1.6/lib/tanker/utilities.rb:38:in`each'
/home/loken/.rvm/gems/ruby-2.1.0@corental/gems/tanker-1.1.6/lib/tanker/utilities.rb:38:in `reindex_all_models'
/home/loken/.rvm/gems/ruby-2.1.0@corental/gems/tanker-1.1.6/lib/tanker/tasks/tanker.rake:7:in`block (2 levels) in <top (required)>'

**Comment by biske** [comment]
+1
I have same problem with exact same gem version.
